Set TZ environment variable
This is an attempt to fixup the following CI error

* building 'R2MultiBUGS_0.9.tar.gz'
Error in strptime(xx, f, tz = tz) : 
  (converted from warning) unable to identify current timezone 'C':
please set environment variable 'TZ'
Error: Failed to install 'R2MultiBUGS' from GitHub:
  (converted from warning) installation of package 'C:/Users/VSSADM~1/AppData/Local/Temp/RtmpCQX0jb/file41c3293e0b/R2MultiBUGS_0.9.tar.gz' had non-zero exit status
Execution halted